version: 0.2

env:
  variables:
    SOLUTION: .\ShoppingBasket.sln
    PACKAGE_DIRECTORY: .\packages
    DOTNET_FRAMEWORK: 4.6.1

phases:
  build:
    commands:
            - dotnet build -c Release ./ShoppingBasket.sln
artifacts:
  files:
    - .\ShoppingBasket\bin\Debug\*
